version: "3"
virtualmachines:
- name: crc
  image: rhd-devx-instruqt/openshift-4-16-7
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
