version: "3"
virtualbrowsers:
- name: rhd-login-3882386
  url: https://developers.redhat.com/node/284339?auHash=5k9QV-yD0z-jAU7XkJyq1TUxhVyyZVLiuZz7tsfTz_s&offerid=3882386
containers:
- name: container
  image: fedora
  shell: /bin/bash
virtualmachines:
- name: crc
  image: rhd-devx-instruqt/openshift-4-17-0
  machine_type: n1-highmem-4
  allow_external_ingress:
  - http
  - https
  - high-ports
  provision_ssl_certificate: true
