version: "3"
containers:
- name: container
  image: fedora
  shell: /bin/bash
virtualmachines:
- name: crc
  image: rhd-devx-instruqt/openshift-4-17-0
  shell: /bin/bash
  machine_type: n1-highmem-8
  allow_external_ingress:
  - http
  - https
  - high-ports
